merchex/merchex/urls.py
from django.contrib import admin
from django.urls import path
from listings import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bands/', views.band_list, name='band-list'),
    path('bands/<int:id>/', views.band_detail, name='band-detail'),
    path('about-us/', views.about),
    path('listings/', views.listings),
    path('listings/<int:id>/', views.listing_detail, name='listing-detail'),
    path('contact-us/', views.contact),
]

merchex/listings/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.
class Band(models.Model):

    class Genre(models.TextChoices):
        HIP_HOP = 'HH'
        SYNTH_POP = 'SP'
        ALTERNATIVE_ROCK = 'AR'
    
    

    name = models.fields.CharField(max_length=100)
    genre = models.fields.CharField(choices=Genre.choices, max_length=5)
    biography = models.fields.CharField(max_length=1000)
    year_formed = models.fields.IntegerField(
        validators=[MinValueValidator(1900), MaxValueValidator(2023)]
    )
    active = models.fields.BooleanField(default=True)
    official_homepage = models.fields.URLField(null=True, blank=True)
    #description = models.fields.CharField(max_length=1000)
    #sold = models.fields.BooleanField(default=False)
    #year = models.fields.IntegerField(
    #    validators=[MinValueValidator(1900), MaxValueValidator(2023)],
    #    null=True)
    

    # definition de l'affichage dns l'administration
    def __str__(self):
        return f'{self.name}'
    


class Listing(models.Model):

    class Type(models.TextChoices):
        Records = 'Disques'
        Clothing = 'Vetements'
        Posters = 'Affiches'
        Miscellaneous = 'Divers'

    title = models.fields.CharField(max_length=100)
    description = models.fields.CharField(max_length=1000)
    sold = models.fields.BooleanField(default=False)
    year = models.fields.IntegerField(
        validators=[MinValueValidator(1900), MaxValueValidator(2023)],
        null=True
    )
    type = models.fields.CharField(choices=Type.choices, max_length=20)

    band = models.ForeignKey(Band, null=True, on_delete=models.SET_NULL)

    # definition de l'afichage dans l'administration
    def __str__(self):
        return f'{self.title}'

merchex/listings/views.py
from django.http import HttpResponse
from django.shortcuts import render
from listings.models import Band
from listings.models import Listing

def band_list(request):
    bands = Band.objects.all()
    return render(request,
                'listings/band_list.html',
                {'bands': bands},
            )

def band_detail(request, id):
    band = Band.objects.get(id = id)
    return render(request,
                  'listings/band_detail.html',
                  {'band' : band})

def about(request):
    return render(request,
                  'listings/about.html')

def listings(request):
    listings = Listing.objects.all()
    return render(request,
                  'listings/listings.html',
                  {'listings': listings},
                )

def listings_detail(request, id):
    listing = Listing.objects.get(id = id)
    return render(request,
                  'listings/listings_detail.html',
                  {'listing':listing})

def contact(request):
    return render(request, 'listings/contact.html')

merchex/listings/templates/listings/about.html
{% extends 'listings/base.html' %}

{% block content %}
        <h1>A propos</h1>
        <p>Nous adorons Merch !</p>
{% endblock %}

merchex/listings/templates/listings/band_detail.html
{% extends 'listings/base.html' %}

{% block content %}
    <h2>{{ band.name }}</h2>

    <ul>
        <li>genre : {{ band.get_genre_display }}</li>
        <li>Année de formation : {{ band.year_formed }}</li>
        <li>Actif : {{ band.active|yesno }}</li>
        {% if band.official_homepage %}
            <li><a href="{{ band.official_homepage }}">{{ band.official_homepage }}</a></li>
        {% endif %}
    </ul>

    <p>{{ band.biography }}</p>

    <div>
        <a href="{% url 'band-list' %}">Retour à la liste des groupes</a>
    </div>
{% endblock %}

merchex/listings/templates/listings/band_list.html
{% extends 'listings/base.html' %}

    {% block content %}
        <h1>Hello Django !</h1>
        <p>
            Mes groupes preférés qui sont :
        </p>
        <!-- TODO : liste des groupes -->
        <ul>
            {% for band in bands %}
                <li><a href="{% url 'band-detail' band.id %}">{{ band.name|upper }}</a></li>
            {% endfor %}
        </ul>
    {% endblock %}

merchex/listings/templates/listings/base.html
{% load static %}

<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static './listings/style.css' %}">
    <title>Merchex</title>
</head>
<body>
    <nav>
        <a href="{% url 'band-list' %}">Les groupes</a>
    </nav>
    {% block content %}
    {% endblock %}
</body>
</html>

merchex/listings/templates/listings/contact.html
{% extends 'listings/base.html'}

{% block content %}
        <h1>Nous contacter</h1>
        <p>Prochainement un formulaire</p>
{% endblock %}

merchex/listings/templates/listings/hello.html
{% extends 'listings/base.html' %}

    {% block content %}
        <h1>Hello Django !</h1>
        <p>
            Mes groupes preférés qui sont :
        </p>
        <!-- TODO : liste des groupes -->
        <ul>
            {% for band in bands %}
                <li>{{ band.name|upper }}</li>
            {% endfor %}
        </ul>
    {% endblock %}

merchex/listings/templates/listings/listing_detail.html
{% extends 'listings/base.html' %}

{% block content %}
    <h2>{{ listing.title }}</h2>

    <p>Description : {{ listing.description }}</p>

    <ul>
        <li>En vente : {{ listing.sold|yesno }}</li>
        <li>Année : {{ listing.year }}</li>
        <li>Type :  {{ listing.get_type_display }}</li>
    </ul>

    <p>Objet du groupe <b>{{ listing.band }}</b></p>

    
{% endblock %}

merchex/listings/templates/listings/listings.html
{% extends 'listings/base.html' %}
{% block content %}
        <h1>Mes listings</h1>
        <p>j'ai {{ listings|length }} listes.</p>
        <p>j'ai
            {% if listings|length < 5 %}
                peu de 
            {% elif listings|length < 10 %}
                 quelques 
            {% else %}
                 beaucoup 
            {% endif %}
            de listes qui sont :
        </p>
        <!-- TODO : liste des groupes -->
        <ul>
            {% for listing in listings %}
                <li><a href="url 'listing-detail' listing.id">{{ listing.title|upper }}</a></li>
            {% endfor %}
        </ul>
{% endblock %}